{% set name = "install-locked-env" %}
{% set version = "0.3.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/install_locked_env-{{ version }}.tar.gz
  sha256: 8b56a620b3b80d4fb78cff18c4497e45bc5b85b39fae2fa7d83c1a85c6703439

build:
  entry_points:
    - install-locked-env = install_locked_env:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }}
    - typer >=0.9.0
    - httpx >=0.27.0
    - rich >=13.0.0
    - requests >=2.32.5

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - install_locked_env
  commands:
    - pip check
    - install-locked-env --help

about:
  summary: Helper to install (web) locked environments
  home: https://foss.heptapod.net/fluiddyn/install-locked-env
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - paugier
